### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ThomasPasquali** [ThomasPasquali/PE#1]
- [ ] Impostazioni: metodi apertura schede
- [ ] Report pratiche tec
- [ ] Inserimento pratiche tec
- [ ] Modifica pratiche
- [ ] Phpmyadmin solo administrator
- [ ] Ricerca pratiche home
- [ ] Submit form barra utils
- [ ] Oneri
- [ ] Stile e colori
